spring: 
 datasource:
   url: jdbc:postgresql://localhost:5433/cards
   username: postgres
   password: 1234567
   properties:
     hibernate:
       jdbc:
         lob:
           non_contextual_creation: true
     javax:
        persistence:
          schema-generation:
            create-source: metadata
            scripts:
              action: create
              create-target: create.sql
          hibernate:
            hbm2ddl:
              delimiter: ";"      
   jpa:
     properties:
       hibernate:
         ddl-auto: none

        

