datasource:
  url: jdbc:postgresql://hr-email-pg12:5432/cards
  username: postgres
  password: 1234567
  properties:
    hibernate:
      jdbc:
        lob:
          non_contextual_creation: true
  jpa:
    properties:
      hibernate:
        ddl-auto: none

spring:
  jpa:
    properties:
      javax:
        persistence:
          schema-generation:
            create-source: metadata
            scripts:
              action: create
              create-target: create.sql
          hibernate:
            hbm2ddl:
              delimiter: ";"                   

        

