spring: 
 datasource:
   url: jdbc:postgresql://localhost:5433/email
   username: postgres
   password: 1234567
   properties:
     hibernate:
       jdbc:
         lob:
           non_contextual_creation: true
   jpa:
     properties:
       hibernate:
         ddl-auto: none

        

