datasource:
  url: jdbc:postgresql://hr-user-pg12:5432/user
  username: postgres
  password: 1234567
  properties:
    hibernate:
      jdbc:
        lob:
          non_contextual_creation: true
  jpa:
    properties:
      hibernate:
        ddl-auto: none
