spring:
  datasource:
    url: jdbc:h2:mem:testdb://localhost/~/testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;webAllowOthers=true
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console/users
